[package]
name = "passphrase"
version = "1.0"
authors = ["Charles Chege <charleschege@protonmail.ch>"]
edition = "2018"

[dependencies]
rand = "0.6.5"
termion = "1.5.1"
zxcvbn = "1.0.1"
yansi = "0.5.0"
